### ISSUE TITLE
Add more notification events

### ISSUE THREAD

**Issue by stephaniejue** [stephaniejue/VolunteerUP#278]

**Comment by sslampa** [comment]
I added notifications for the following event triggers:

- User first joins the event
- User first joins the waitlist for an event
- Organization is updated
- Creator removes organizers from an org
- Organizers remove themselves from an org
- Organizer removes a volunteer from an event

If you think there should be anymore of these, let me know, otherwise I think we've covered pretty much every event that doesn't involve doing some cron job
